// The workspace clippy.toml rejects the floating-point primitives outright,
// which is what keeps them out of the simulation. This crate is the one place
// allowed to use them, and it says so here, locally, rather than by loosening
// the shared configuration: the ban has to stay total everywhere else.
#![allow(clippy::disallowed_types)]

//! Offline generator of the sine table that `fablegen-sim` reads.
//!
//! The crate sits outside `sim/` on purpose. Floating point is banned across
//! the whole simulation crate -- by clippy and by the CI grep gate, which is
//! aimed at `sim/` as a directory -- while computing a sine needs it. So the
//! table is computed here, once, off the hot path, and committed to the
//! repository as data. Nothing recomputes it at startup.
//!
//! Regenerate the committed file with:
//!
//! ```text
//! cargo run -p gen-trig-table > sim/src/trig_table.rs
//! ```

use std::f64::consts::TAU;
use std::fmt::Write as _;

/// Divisions of the full circle: the length of the table and the size of the
/// angle index space the simulation uses.
const TABLE_LEN: usize = 1024;

/// Fixed-point scale of the simulation, Q10.
///
/// Mirrors `fablegen_sim::fixed::SCALE` rather than importing it, because this
/// crate cannot depend on the simulation (see Cargo.toml). The copy is not left
/// unchecked: the simulation's own reference-point test compares `SIN[256]`
/// against the real `SCALE`, so a mismatch here fails over there.
const SCALE: i32 = 1024;

/// Values printed per line of the generated file.
const VALUES_PER_LINE: usize = 8;

/// Header of the generated file, up to and including the blank line before the
/// constant.
const HEADER: &str = "\
// Generated by tools/gen-trig-table. Do not edit by hand.
//
// sin(2 * PI * i / 1024) scaled by 1024 (Q10) for i in 0..1024, rounded to the
// nearest integer with ties away from zero.
//
// That rounding is not the floor rule of DETERMINISM.md #2 and does not weaken
// it. Floor governs Fx arithmetic in the hot path; this table is computed offline,
// once, and frozen as data. Ties away from zero is what keeps the table exactly
// antisymmetric, SIN[(1024 - i) % 1024] == -SIN[i]: floor would push the whole
// table toward negative infinity and break that symmetry.
//
// Regenerate with:
//
//     cargo run -p gen-trig-table > sim/src/trig_table.rs
//
// Nothing here is evaluated at startup: no lazy initialisation, no constructor.
// The values ARE the data. See DETERMINISM.md #4.
//
// rustfmt is kept off the array on purpose: the layout belongs to the
// generator, and a future rustfmt version must not rewrite committed data into
// a diff that reads like a change to the table.

";

/// Rounds to the nearest integer, breaking ties away from zero.
///
/// Written out rather than borrowed from the standard library. A cast truncates
/// toward zero, which is a different function; and what a library rounding call
/// does on an exact tie is a property this table must not silently inherit.
/// Ties away from zero is the choice, because it is the one that negates
/// cleanly: rounding `-x` gives exactly minus the rounding of `x`, which is
/// what makes the finished table exactly antisymmetric.
fn round_ties_away_from_zero(value: f64) -> i64 {
    let magnitude = value.abs();
    let whole = magnitude.floor();
    let fraction = magnitude - whole;

    // `whole` is a non-negative integral value far below the range where i64
    // stops holding every integer, so this conversion is exact rather than
    // truncating: the truncation happened in `floor`, deliberately and visibly.
    let mut rounded = whole as i64;
    if fraction >= 0.5 {
        rounded += 1;
    }

    if value.is_sign_negative() {
        -rounded
    } else {
        rounded
    }
}

/// The sine of one angle step, scaled to Q10 but not yet rounded.
///
/// Kept separate from the table so that the tests can measure how far each
/// value sits from a rounding boundary, which is what makes the exact
/// comparison safe to run on a platform other than the one that generated the
/// committed file.
fn scaled_sine(index: usize) -> f64 {
    let angle = TAU * (index as f64) / (TABLE_LEN as f64);
    angle.sin() * f64::from(SCALE)
}

/// Computes the whole table: the sine of every one of the 1024 angle steps,
/// scaled to Q10.
fn sine_table() -> [i32; TABLE_LEN] {
    let mut table = [0_i32; TABLE_LEN];

    for (index, slot) in table.iter_mut().enumerate() {
        let rounded = round_ties_away_from_zero(scaled_sine(index));
        *slot = i32::try_from(rounded).expect("a sine scaled by 1024 stays well inside i32");
    }

    table
}

/// Renders the generated source file: header comment plus the constant.
fn render(table: &[i32; TABLE_LEN]) -> String {
    let mut out = String::from(HEADER);

    out.push_str("#[rustfmt::skip]\n");
    writeln!(out, "pub(crate) const SIN: [i32; {TABLE_LEN}] = [")
        .expect("writing into a String cannot fail");

    for chunk in table.chunks(VALUES_PER_LINE) {
        out.push_str("   ");
        for value in chunk {
            write!(out, " {value:>5},").expect("writing into a String cannot fail");
        }
        out.push('\n');
    }

    out.push_str("];\n");
    out
}

fn main() {
    print!("{}", render(&sine_table()));
}

#[cfg(test)]
mod tests {
    use super::{render, round_ties_away_from_zero, scaled_sine, sine_table, SCALE, TABLE_LEN};

    // The table exactly as it is committed. Included as source rather than
    // reached through the library, because `SIN` is `pub(crate)` in
    // fablegen-sim and stays that way: the simulation reads it through
    // `trig::sin`, not by indexing the array.
    mod committed {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../sim/src/trig_table.rs"
        ));
    }

    /// Compares a table against the committed one value by value.
    ///
    /// Takes the table as an argument instead of reaching for the constant, so
    /// that the negative probes below can hand it a corrupted copy and require
    /// a failure. A check nobody has ever seen fail is not known to check
    /// anything.
    fn compare_with_committed(table: &[i32; TABLE_LEN]) -> Result<(), String> {
        for (index, (fresh, stored)) in table.iter().zip(committed::SIN.iter()).enumerate() {
            if fresh != stored {
                return Err(format!(
                    "index {index}: recomputed {fresh}, committed {stored}"
                ));
            }
        }
        Ok(())
    }

    #[test]
    fn the_committed_table_is_exactly_what_this_generator_computes() {
        // This is the exact half of the two checks on the table: the
        // simulation's own tests prove the table obeys the invariants of a
        // sine, and this one proves it is this generator's output and not
        // something typed in by hand.
        //
        // It recomputes through the platform's own sine, which is the very
        // thing DETERMINISM.md #4 refuses to trust in the hot path. That is
        // deliberate and the direction of trust is one-way: the committed data
        // is authoritative, and this test is a tripwire on the generator. If it
        // ever fails on a platform whose library disagrees in the last bit, the
        // answer is not to regenerate the table.
        compare_with_committed(&sine_table())
            .expect("the committed table drifted from the generator");
    }

    #[test]
    fn probe_one_value_shifted_by_one_fails_the_comparison() {
        let mut table = sine_table();
        let committed_137 = table[137];
        table[137] += 1;
        let error = compare_with_committed(&table)
            .expect_err("a table one unit off at index 137 passed the exact comparison");
        // Not just "some error": the message has to name the damage, or the
        // probe would stay green on a comparison that broke for another reason.
        assert_eq!(
            error,
            format!(
                "index 137: recomputed {}, committed {committed_137}",
                committed_137 + 1
            )
        );
    }

    #[test]
    fn probe_a_rotation_by_one_step_fails_the_comparison() {
        let table = sine_table();
        let mut rotated = [0_i32; TABLE_LEN];
        for (index, slot) in rotated.iter_mut().enumerate() {
            *slot = table[(index + 1) % TABLE_LEN];
        }
        let error = compare_with_committed(&rotated)
            .expect_err("a table rotated by one step passed the exact comparison");
        assert_eq!(
            error,
            format!("index 0: recomputed {}, committed {}", table[1], table[0])
        );
    }

    /// How far every value must sit from the boundary where rounding flips.
    ///
    /// The exact comparison above recomputes the table through the platform's
    /// own sine. The committed file was generated on one operating system and
    /// CI recomputes it on another, so the two only agree if no value sits so
    /// close to a `.5` boundary that a last-bit disagreement between libm
    /// implementations pushes it across.
    ///
    /// The margin is a bound, not a measurement, and it is set enormously
    /// wider than anything that could go wrong. A double near 1024 has an ULP
    /// of `2^-42`, about `2.3e-13`. Sine implementations that disagree at all
    /// disagree by a few ULP; even an absurdly loose hundred ULP is `2.3e-11`.
    /// This margin is `1e-6`, roughly four million ULP -- five orders of
    /// magnitude of headroom. It is deliberately not fitted to the measured
    /// minimum: it is a line drawn far above the noise floor, and the
    /// measurement has to clear it by a wide margin of its own.
    const ROUNDING_MARGIN: f64 = 1.0e-6;

    /// Distance from a value to the nearest point where rounding would flip.
    ///
    /// Rounding acts on the magnitude, so the fraction is taken there too.
    fn distance_to_a_rounding_boundary(value: f64) -> f64 {
        let magnitude = value.abs();
        let fraction = magnitude - magnitude.floor();
        (fraction - 0.5).abs()
    }

    /// The smallest such distance across the whole table.
    fn smallest_distance_to_a_rounding_boundary() -> (usize, f64) {
        let mut worst_index = 0;
        let mut worst = f64::INFINITY;

        for index in 0..TABLE_LEN {
            let distance = distance_to_a_rounding_boundary(scaled_sine(index));
            if distance < worst {
                worst = distance;
                worst_index = index;
            }
        }

        (worst_index, worst)
    }

    #[test]
    fn no_value_sits_near_a_rounding_boundary() {
        let (index, distance) = smallest_distance_to_a_rounding_boundary();

        // Not a warning, a hard failure. If this ever trips, the exact
        // comparison is no longer safe to run on a foreign platform: it could
        // go red with nothing actually wrong, and the right answer would be to
        // decide what to do about the check, not to regenerate the table.
        assert!(
            distance > ROUNDING_MARGIN,
            "index {index} sits {distance:e} from a rounding boundary, inside the \
             {ROUNDING_MARGIN:e} margin: a libm disagreeing in the last bit could round \
             it the other way, and the exact comparison would go red on another \
             platform without anything being wrong"
        );
    }

    #[test]
    fn the_margin_measurement_can_see_a_value_on_the_boundary() {
        // The measurement above is only worth its green tick if it would
        // notice a value sitting on a boundary. Half-integers are exactly
        // those, and they must measure as zero distance.
        assert_eq!(distance_to_a_rounding_boundary(0.5), 0.0);
        assert_eq!(distance_to_a_rounding_boundary(-7.5), 0.0);
        assert_eq!(distance_to_a_rounding_boundary(723.5), 0.0);
        // And a value in the clear must measure as far from it.
        assert_eq!(distance_to_a_rounding_boundary(7.0), 0.5);
        assert_eq!(distance_to_a_rounding_boundary(-7.25), 0.25);
    }

    #[test]
    fn rounding_breaks_ties_away_from_zero() {
        // The ties are the whole point: nearest-even would send 0.5 to 0 and
        // 2.5 to 2, and truncation would send -0.5 to 0.
        assert_eq!(round_ties_away_from_zero(0.5), 1);
        assert_eq!(round_ties_away_from_zero(-0.5), -1);
        assert_eq!(round_ties_away_from_zero(1.5), 2);
        assert_eq!(round_ties_away_from_zero(-1.5), -2);
        assert_eq!(round_ties_away_from_zero(2.5), 3);
        assert_eq!(round_ties_away_from_zero(-2.5), -3);
    }

    #[test]
    fn rounding_negates_exactly() {
        // The property the table's antisymmetry rests on, checked over a range
        // that includes both tie and non-tie fractions.
        for step in -4096..=4096 {
            let value = f64::from(step) / 8.0;
            assert_eq!(
                round_ties_away_from_zero(-value),
                -round_ties_away_from_zero(value),
                "rounding did not negate cleanly at {value}"
            );
        }
    }

    #[test]
    fn rounding_leaves_values_below_a_half_alone() {
        assert_eq!(round_ties_away_from_zero(0.0), 0);
        assert_eq!(round_ties_away_from_zero(0.499), 0);
        assert_eq!(round_ties_away_from_zero(-0.499), 0);
        assert_eq!(round_ties_away_from_zero(1.499), 1);
        assert_eq!(round_ties_away_from_zero(-1.499), -1);
        assert_eq!(round_ties_away_from_zero(1.501), 2);
        assert_eq!(round_ties_away_from_zero(-1.501), -2);
    }

    #[test]
    fn the_rendered_file_carries_every_value_in_order() {
        let table = sine_table();
        let rendered = render(&table);

        // The last '[' in the file opens the array: everything after it is
        // digits, signs, commas and whitespace up to the closing bracket.
        let (_, body) = rendered
            .rsplit_once('[')
            .expect("the rendered array must open with a bracket");
        let (body, _) = body
            .split_once(']')
            .expect("the rendered array must close with a bracket");

        let printed: Vec<i32> = body
            .split(',')
            .map(str::trim)
            .filter(|piece| !piece.is_empty())
            .map(|piece| piece.parse().expect("every printed value must parse back"))
            .collect();

        assert_eq!(
            printed.len(),
            TABLE_LEN,
            "the printer dropped or added values"
        );
        assert_eq!(printed.as_slice(), table.as_slice());
    }

    #[test]
    fn the_rendered_file_warns_against_editing_it() {
        let rendered = render(&sine_table());
        assert!(rendered.starts_with("// Generated by tools/gen-trig-table."));
        assert!(rendered.contains("Do not edit by hand."));
        assert!(rendered.contains("cargo run -p gen-trig-table > sim/src/trig_table.rs"));
    }

    #[test]
    fn the_mirrored_scale_matches_the_peak_of_the_committed_table() {
        // The local copy of SCALE cannot be imported from the simulation, so it
        // is pinned from this side too: a quarter turn into the table is where
        // the sine reaches one, which in Q10 is SCALE itself.
        assert_eq!(committed::SIN[TABLE_LEN / 4], SCALE);
    }
}
